Covid 19 Plan Definition Examples in Storybook
medplum/medplum pull request #1043
Opened 2022-10-10 21:19 UTC by rahul1

2022-10-10 21:25 UTC, reshmakh commented on packages/react/src/stories/PlanDefinitionBuilder.stories.tsx
> +      value={Covid19CarePlanDefinition}
Looking at the storybook, looks like the PD.actions do not have timings.  Possible to add them?

2022-10-10 21:27 UTC, reshmakh commented
Is there a way to represent that this item is done by a physician? https://medplum-storybook-8gxlou26o-medplum.vercel.app/?path=/docs/medplum-resourcetable--covid-19-review-report-activity

2022-10-10 21:28 UTC, reshmakh commented
Show code doesn't work for this https://medplum-storybook-8gxlou26o-medplum.vercel.app/?path=/docs/medplum-resourcetable--covid-19-review-report-activity

2022-10-10 21:36 UTC, reshmakh commented
Some additional nits on the copy for https://medplum-storybook-8gxlou26o-medplum.vercel.app/?path=/docs/medplum-plandefinitionbuilder--covid-19-eval

Could be made a bit more descriptive and in line with protocols I have seen

Title: COVID-19 Evaluation Pre-Admission to Inpatient Oncology Department
Patient Follow Up: Patient admission appointment with specialist

2022-10-10 21:40 UTC, rahul1 commented
@reshmakh I'm seeing the Show Code here. Are you seeing something different? 
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/1259236/194956506-5df5c2d5-a965-4c09-8446-997ec1ee9ef9.png">

2022-10-10 22:16 UTC, rahul1 commented
> Is there a way to represent that this item is done by a physician? https://medplum-storybook-8gxlou26o-medplum.vercel.app/?path=/docs/medplum-resourcetable--covid-19-review-report-activity

There's not a great way, but I did add a `participant` property to the action to indicate this

2022-10-11 17:35 UTC, codyebberson requested changes
Can we move `covid19.ts` into `packages/react/src/stories/`?  You can add the resources to the mock repository in the Storybook story.  In my opinion, we don't need to preload them into the mock repo (we should probably have a longer converasation about what should be included there).

Stories are ignored by Sonar, so that also will take care of the security hotspots and duplication warnings.

Alternatively, you can sign into Sonar and mark them as "safe" because we're not using the URL's for requests.

2022-10-11 20:33 UTC, codyebberson approved these changes

2022-10-11 21:34 UTC, merged