Bugfix: useResource makes incorrect fetch when called with resource with id
medplum/medplum pull request #1583
Opened 2023-02-23 06:31 UTC by rahul1

Before: 
calling `useResource({resourceType: 'ServiceRequest', id: '123'})` would always fetch from the server, even if the resource had been modified on the client.

After: 
If calling with a resource that has been modified client-side, re-render if `deepEquals` fails

2023-02-23 17:19 UTC, codyebberson requested changes
Let's discuss offline.  I think there's a philosophical disconnect in the purpose of `useResource()`.  The behavior here doesn't align with my expectations.  My expectations might be wrong, but we should figure that out first.

2023-03-01 17:12 UTC, codyebberson commented
Summarizing my thoughts:

>  would always fetch from the server, even if the resource had been modified on the client

At this point, your component is managing its own state, and should use `React.useState`, not depend on `useResource`.

We could review the developer experience of `useResource` + `useState` -- for example, in cases where you want `useState` to start the the most fresh data, but you want to be able to manipulate the data.

Consider the setup code in `<ResourceForm>` (https://github.com/medplum/medplum/blob/main/packages/react/src/ResourceForm/ResourceForm.tsx#L17-L28):

```tsx
  const medplum = useMedplum();
  const defaultValue = useResource(props.defaultValue);
  const [schema, setSchema] = useState<IndexedStructureDefinition | undefined>();
  const [value, setValue] = useState<Resource | undefined>();

  useEffect(() => {
    if (defaultValue) {
      setValue(JSON.parse(JSON.stringify(defaultValue)));
      medplum.requestSchema(defaultValue.resourceType).then(setSchema).catch(console.log);
    }
  }, [medplum, defaultValue]);
```

2023-03-03 23:40 UTC, rahul1 commented
The problem arises when you have a parent component that calls a child that uses `useResource`. Even if the parent is managing it's own state with `useState` and passes the modified resource to a child component, it will ignore what was passed in and read from cache instead. 

This breaks the parent/child abstraction. The implementer of the parent needs to:
1. Know that the child component uses `useResource`
2. Know that `useResource` will read from cache if the `Resource.id` property is set
3. Delete the `Resource.id` property from the resource in memory, before passing it as a prop to child. 

That requires too much knowledge about the internals of both the child and `useResource`

2023-03-04 00:02 UTC, codyebberson commented
> Even if the parent is managing it's own state with `useState` and passes the modified resource to a child component, it will ignore what was passed in and read from cache instead.

`useResource` and the `MedplumClient` cache are for "live" data.  In this example, if the parent is managing state and wants to share state with the child, it should pass the modified resource as a prop.

`useResource` is for "I want the most recent version of this resource".

2023-03-05 05:25 UTC, rahul1 commented
Closing in favor of #1622

2023-03-05 05:25 UTC, closed without merging