Add bundle to resource array in MedplumClient
medplum/medplum pull request #2445
Opened 2023-07-12 16:11 UTC by codyebberson

2023-07-12 16:42 UTC, mattwiller commented
What's the advantage of this approach vs. using the `client.search()` method to retrieve the actual `Bundle`?

2023-07-12 17:16 UTC, rahul1 requested changes
I was initially opposed, but I'm now convinced!

Reminder to document on the "Basic Search" and "Paginated Search" guides

2023-07-12 17:50 UTC, codyebberson commented
> What's the advantage of this approach vs. using the `client.search()` method to retrieve the actual `Bundle`?

See the Slack thread for customer description.

Using `client.search()` is a reasonable suggestion.  `Bundle` just has known friction (need to navigate `.entry`, need to cast `.resource`, etc).

2023-07-12 17:50 UTC, codyebberson commented
> Reminder to document on the "Basic Search" and "Paginated Search" guides

Done ✅

2023-07-12 18:46 UTC, mattwiller commented
I would prefer deprecating the `searchResources()` method and adding a new one that presents an async iterator over all search results with the required properties attached, rather than monkey-patching a builtin JS type.  If for some reason the language ever adds an `Array.prototype.bundle()` method, the approach in this PR would result in a conflict

2023-07-13 00:57 UTC, codyebberson commented
@mattwiller 

> I would prefer deprecating the `searchResources()` method

`searchResources()` is very popular and widely used (including by many of our own sample apps and demo bots).  This isn't really an option.

> adding a new one that presents an async iterator over all search results with the required properties attached

This kind of exists in `searchResourcePages()`: https://www.medplum.com/docs/sdk/classes/MedplumClient#searchresourcepages

> If for some reason the language ever adds an Array.prototype.bundle() method

This is valid, although unlikely IMHO.

Would `.fhirBundle` be better?  `.originalBundle`?  `._bundle`?

Note that "pagination" is only one part of the use case of "total".  There are many UI cases where you want to show a count.

2023-07-13 02:19 UTC, rahul1 approved these changes

2023-07-13 20:55 UTC, merged