[Photon Health] Sync patients from Photon
medplum/medplum pull request #5580
Opened 2024-11-22 15:36 UTC by ksmith94

This PR creates a bot that syncs patients from Photon into Medplum. 
This is still a work in progress as the UI needs to be updated to include a way to execute the bot. Scripts also need to be updated to include this bot.

2024-11-26 21:47 UTC, rahul1 requested changes

2024-11-26 21:47 UTC, rahul1 commented on examples/medplum-photon-integration/src/bots/sync-patient-from-photon.ts
> +    if (!(await checkForExistingPatient(photonPatient, medplum))) {
I think we should still sync the patient's allergies and medications even if the patient already exists. We just don't want to update the `Patient` resource

2024-11-26 21:47 UTC, rahul1 commented on examples/medplum-photon-integration/src/bots/sync-patient-from-photon.ts
> +      resourceType: 'AllergyIntolerance',
We should also add `meta.source=<PHOTON_URL>` to the `AllergyIntolerance` and `MedicationRequest` . this is a searchable parameter that can be used for upsert

2024-12-02 14:58 UTC, ksmith94 commented on examples/medplum-photon-integration/src/bots/sync-patient-from-photon.ts
> +export function createAllergies(
Photon tracks a patient's allergies using a [PatientAllergy](https://reference.photon.health/#definition-PatientAllergy), which doesn't have an id, so there's unfortunately no way to add an identifier for allergies.

2024-12-12 20:07 UTC, rahul1 commented on examples/medplum-photon-integration/src/bots/sync-patient-from-photon.ts
> +            url: `AllergyIntolerance?_source=${NEUTRON_HEALTH}&code=${allergy.code}&patient=${allergy.patient.reference}`,
I got some guidance that we shouldn't be using `urn:uuid` references in the `url` during an upsert. 

Instead, we should be using chained search like this: 
`patient.identifier=${NEUTRON_HEALTH_PATIENTS}|${photonPatient.id}`

2024-12-12 20:11 UTC, rahul1 approved these changes
requested one change re: upserting Allergies

2024-12-19 20:58 UTC, ThatOneBro commented
Hi @ksmith94 , do you mind rebasing this branch before attempting to merge again. 
Looks like some recent change in `main` is causing your branch to fail merge checks for `eslint` even though CI passed on this branch before merge. 

<img width="872" alt="Screenshot 2024-12-19 at 12 56 54 PM" src="https://github.com/user-attachments/assets/716a895c-2e43-44c3-86f3-dc3168c14b1d" />

2024-12-20 15:50 UTC, merged