Updated "Create FHIR Data" to use TS Client
medplum/medplum pull request #947
Opened 2022-09-06 20:16 UTC by rahul1

2022-09-06 23:38 UTC, codyebberson commented on packages/docs/docs/tutorials/api-basics/create-fhir-data.md
> +  resourceType: 'DiagnosticReport',
`status` is a required field

2022-09-06 23:39 UTC, codyebberson requested changes
Let's add the required fields to prepare for strict mode

2022-09-06 23:39 UTC, codyebberson commented on packages/docs/docs/tutorials/api-basics/create-fhir-data.md
> +    resourceType: 'Observation',
Add `status`

2022-09-06 23:39 UTC, codyebberson commented on packages/docs/docs/tutorials/api-basics/create-fhir-data.md
> +    resourceType: 'Observation',
Add `status`

2022-09-06 23:43 UTC, rahul1 commented on packages/docs/docs/tutorials/api-basics/create-fhir-data.md
> +  resourceType: 'DiagnosticReport',
Good catch

2022-09-07 01:06 UTC, codyebberson approved these changes

2022-09-07 01:17 UTC, merged