Updated README with auth and bots descriptions
medplum/medplum pull request #974
Opened 2022-09-12 17:14 UTC by codyebberson

2022-09-13 04:21 UTC, rahul1 approved these changes

2022-09-13 04:22 UTC, rahul1 requested changes
@codyebberson Can you square this with home.md page on our docs? Our docs don't mention Auth, and this README doesn't seem to mention the API

2022-09-13 16:06 UTC, codyebberson commented
> Our docs don't mention Auth

?

https://www.medplum.com/docs/api/oauth

2022-09-13 17:08 UTC, rahul1 commented
I meant on `home.md`

https://www.medplum.com/docs

2022-10-11 18:37 UTC, rahul1 approved these changes

2022-10-11 21:29 UTC, merged